-- DROP TABLE `Follows`;
-- DROP TABLE `Comment`;
-- DROP TABLE Entry;
-- DROP TABLE Journal;
-- DROP TABLE Mood;
-- DROP TABLE Weather;
-- DROP TABLE `User`;
-- DROP TABLE Gender;
-- DROP TABLE Location;

CREATE DATABASE Travel_Journal;
USE Travel_Journal;

CREATE TABLE Gender (
    GID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Gname VARCHAR(16) NOT NULL
);

CREATE TABLE `User` (
	UID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Uname VARCHAR(60) NOT NULL UNIQUE,
    `password` VARCHAR(512) NOT NULL,
    Fname VARCHAR(48) NOT NULL,
    Lname VARCHAR(48) NOT NULL,
    createdTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Bio VARCHAR(256),
    DoB DATE,
    GID INT NOT NULL,
    picturePath VARCHAR(256),
    FOREIGN KEY (GID) REFERENCES Gender (GID) ON DELETE RESTRICT
);

CREATE TABLE Location (
	LID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Lname VARCHAR(128) NOT NULL, 
    googleLocation VARCHAR(700) NOT NULL,
    `address` VARCHAR(128) NOT NULL,
    `withIn` INT,
    `description` VARCHAR(512),
    picturePath VARCHAR(256)
);

CREATE TABLE Mood (
	`MID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Mname VARCHAR(35),
    `description` VARCHAR(128)
);

CREATE TABLE Weather (
	WID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Wname VARCHAR(35),
    `description` VARCHAR(128)
);

CREATE TABLE Journal (
	JID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UID INT NOT NULL,
    LID INT NOT NULL,
    title VARCHAR(48),
    startDate DATE,
    endDate DATE,
    `description` VARCHAR(700),
    createdTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    picturePath VARCHAR(256),
    FOREIGN KEY (UID) REFERENCES `User` (UID) ON DELETE CASCADE,
    FOREIGN KEY (LID) REFERENCES Location (LID) ON DELETE RESTRICT
);

CREATE TABLE Entry (
	JID INT NOT NULL,
    LID INT NOT NULL,
    MID INT,
    WID INT,
    `date` DATE NOT NULL,
    `time` TIME NOT NULL,
    `description` VARCHAR(700),
    FOREIGN KEY (JID) REFERENCES Journal (JID) ON DELETE CASCADE,
    FOREIGN KEY (LID) REFERENCES Location (LID) ON DELETE RESTRICT,
    FOREIGN KEY (MID) REFERENCES Mood (MID) ON DELETE RESTRICT,
    FOREIGN KEY (WID) REFERENCES Weather (WID) ON DELETE RESTRICT
);

CREATE TABLE `Comment` (
	CID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UID INT NOT NULL,
    JID INT NOT NULL,
    commentText VARCHAR(256) NOT NULL,
    commentedTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replyTo INT,
    delFlag BINARY(1),
    FOREIGN KEY (JID) REFERENCES Journal (JID) ON DELETE CASCADE,
    FOREIGN KEY (UID) REFERENCES `User` (UID) ON DELETE CASCADE
);

CREATE TABLE `Follows` (
	UID INT NOT NULL,
    followedUID INT NOT NULL,
	CONSTRAINT CHK_UID CHECK (UID != followedUID),
    FOREIGN KEY (UID) REFERENCES `User` (UID) ON DELETE CASCADE,
    FOREIGN KEY (followedUID) REFERENCES `User` (UID) ON DELETE CASCADE
);